### ISSUE TITLE
Update Readme with details about how to Add/Update generated-sources.json

### ISSUE THREAD

**Issue by andirsun** [flathub/electron-sample-app#12]
Hey!
I was following the [official electron documentation for flatpak](https://docs.flatpak.org/en/latest/electron.html), I realize that this repo does not contain a link to that tutorial (https://github.com/flathub/electron-sample-app/issues/3#issue-802770776) So in order to make this repo more easy to follow for new users building flatpaks like me, we can add information which commands users can use to generate ```generated-sources.json```.

```
 flatpak-node-generator npm package-lock.json 
```

**Comment by cpba** [comment]
You just added a link to the tutorial in https://github.com/flathub/electron-sample-app/pull/13/commits/699671fd356fa7786baf84f4072643ea9bb38cae.

The tutorial already explains how to create the file in the Bundling NPM packages section, should this issue be closed then?
