### ISSUE TITLE
How to set an icon?

### ISSUE THREAD

**Issue by openspeedtest** [flathub/electron-sample-app#5]
How to set an icon for the flatpak application generated from this sample electron app?

**Comment by cpba** [comment]
Generally speaking it's the same as any other app, the icon must be specified in the desktop file and copied to its specified paths depending on size (for instance, a 512px icon would go under ```/app/share/icons/hicolor/512x512/apps/```), ```flatpak-builder``` finds and exports these paths to make them available outside the sandbox.

However, if you're using something like ```electron-builder``` or similar you can do it their way and let it take care of it.

**Comment by openspeedtest** [comment]
In this example we are using electron builder right. 
for some reason when i set an icon via package.json it is not getting reflected on flatpak. 
Can you drop a working json code adding a custom icon for this example app?
that is the final thing i need to fix.

**Comment by cpba** [comment]
> In this example we are using electron builder right.
> for some reason when i set an icon via package.json it is not getting reflected on flatpak.

Sorry I can't really help you with this, but if your issue is specific to ```electron-builder``` you may be able to get help from them.

> Can you drop a working json code adding a custom icon for this example app?

I don't have one, I whipped up this example three years ago in half an hour for a tutorial I was working on.

If you don't want to deal with ```electron-builder``` and would rather do it manually you can do what I was saying earlier, write a desktop file and the icons to their respective paths. The flatpak documentation has a cheat-sheet for this kind of situation: https://docs.flatpak.org/en/latest/freedesktop-quick-reference.html

You can do it directly in your manifest if you want.

**Comment by openspeedtest** [comment]
Looks like with Electron Builder app icon is working on Snap, Appimage etc. but not working when i make a flatpak.
the only way is to do it manually. like you said. But i can't find any example electron app doing that in FlatHub Pull Request. 

but when i try flatpak run org.openspeedtest.server it's running.. but cannot be found or ubuntu app drawer 

I suspect maybe if i install this app properly it may work?

so i try to export but getting another error message. :(   

How to create a .flatpak file from this sample electron app?

flatpak create-usb / org.openspeedtest.server
error: Remote ‘server-origin’ does not have a collection ID set, which is required for P2P distribution of ‘app/org.openspeedtest.server/x86_64/master’.

**Comment by cpba** [comment]
> But i can't find any example electron app doing that in FlatHub Pull Request.

There's a lot of electron apps on flathub, like for instance this one:

https://github.com/flathub/io.github.hmlendea.geforcenow-electron/

You'll notice that repo has an icon and a desktop file and installs both of them manually in the manifest, it's just what you're trying to do.

As for your other questions, this isn't a good place for support, I suggest you drop by https://matrix.to/#flatpak:matrix.org
